home-hero-without-bg
Mykokola/teams-project-17 pull request #1
Opened 2023-02-24 22:36 UTC by AlexandrOvsii

готово, но пока без бэкграунда

2023-02-24 23:18 UTC, Mykokola requested changes
Якщо щось не зрозуміло можем зідзвонити і проговорити 
Думаю зараз варто це пофіксити а дальше будем дивитись
Успіху

2023-02-24 23:18 UTC, Mykokola commented on src/css/pages/home/hero.css
> +  padding-top: 429px;
padding задаємо на секцію а не на заголовок

2023-02-24 23:18 UTC, Mykokola commented on src/css/pages/home/hero.css
> +  padding-bottom: 24px;
тут має бути margin

2023-02-24 23:18 UTC, Mykokola commented on src/css/pages/home/hero.css
> +  text-align: center;
текс не завжди по центру на декстопі він притиснутий зліва

2023-02-24 23:18 UTC, Mykokola commented on src/css/pages/home/hero.css
> +    padding-bottom: 48px;
незнаю що це і для чого ?

2023-02-24 23:18 UTC, Mykokola commented on src/css/pages/home/hero.css
> +    margin-bottom: 76px;
цей margin залишається на декстопі хочу він тут не потрібен він тільки для таблеток

2023-02-24 23:27 UTC, Tasitaforme commented on src/css/pages/home/hero.css
> +    margin-bottom: 76px;
а він не 86?

2023-02-24 23:28 UTC, Tasitaforme commented on src/css/pages/home/hero.css
> +    padding-bottom: 48px;
це падінг, який має бути на секції )))

2023-02-24 23:35 UTC, Mykokola commented on src/css/pages/home/hero.css
> +    margin-bottom: 76px;
78*

2023-02-24 23:37 UTC, Mykokola commented on src/css/pages/home/hero.css
> +    padding-bottom: 48px;
а чому pading а не margin?

2023-02-25 07:24 UTC, AlexandrOvsii commented on src/css/pages/home/hero.css
> +  padding-top: 429px;
виправлено

2023-02-25 07:26 UTC, AlexandrOvsii commented on src/css/pages/home/hero.css
> +  padding-bottom: 24px;
виправлено

2023-02-25 07:28 UTC, AlexandrOvsii commented on src/css/pages/home/hero.css
> +  text-align: center;
виправлено і додано до медіа-правила на хіро тайтл text-align:left:

2023-02-25 07:29 UTC, AlexandrOvsii commented on src/css/pages/home/hero.css
> +    padding-bottom: 48px;
додано до секцій padding-bottom: 40px; і прибрано з .home-hero-list

2023-02-25 07:52 UTC, AlexandrOvsii commented on src/css/pages/home/hero.css
> +    margin-bottom: 76px;
пофіксив

2023-02-25 15:39 UTC, Mykokola requested changes
Я там повводив що треба виправити і можна вже добавляти картинку

2023-02-25 15:39 UTC, Mykokola commented on src/css/pages/home/hero.css
> +.home-hero .container {
краще вішати підінги на секцію а не на контейнер що в ній

2023-02-25 15:39 UTC, Mykokola commented on src/css/pages/home/hero.css
> +  padding-top: 429px;
наш херед спозиціонований і лежить над хіро тому там піднг повнний бути 507

2023-02-25 15:39 UTC, Mykokola commented on src/partials/home/hero.html
> +                <li class="home-hero-item link">Whether you're in the mood for a hearty breakfast, a light lunch, or <span class="home-hero-fs">a romantic dinner</span>, our menu has something for ev
тут можна додатии щоб зробити тег похилим клас ital 
І текст думаб краще було б запхати в тег p

2023-02-26 07:45 UTC, AlexandrOvsii commented on src/css/pages/home/hero.css
> +  padding-top: 429px;
виправлено

2023-02-26 16:45 UTC, Mykokola approved these changes

2023-02-26 16:46 UTC, Mykokola approved these changes

2023-02-26 17:11 UTC, merged