Completed the room-hero section
Mykokola/teams-project-17 pull request #26
Opened 2023-02-27 19:54 UTC by BozhiiKostya

2023-02-27 20:21 UTC, BozhiiKostya commented
Произошел сбой и мой room hero.html не залился.... Сейчас исправлю.

2023-02-27 21:29 UTC, Mykokola requested changes
html розмітку забув закомітити

2023-02-28 04:49 UTC, BozhiiKostya commented
Я же об этом и писал. уже закинул.

2023-02-28 04:52 UTC, Mykokola requested changes
Знаєш може трошки дивна порада але можеш підглянути як робири ресторан хіро

2023-02-28 04:52 UTC, Mykokola commented on src/partials/room/hero.html
> +      <img
картинка не оптимізована подивись як інші їх підключали

2023-02-28 04:52 UTC, Mykokola commented on src/css/pages/room/hero.css
> +    position: absolute;
absolute тут вроді не обовязковий можна флексом нормально зпозицінувати

2023-02-28 17:19 UTC, Mykokola approved these changes

2023-02-28 17:21 UTC, merged