Home restaurant details
Mykokola/teams-project-17 pull request #6
Opened 2023-02-25 19:41 UTC by ViktoriiaProtasova

Стрілочки не додавала, бо для слайдера вони не потрібні

2023-02-25 21:56 UTC, Mykokola requested changes

2023-02-25 21:56 UTC, Mykokola commented on src/partials/home/restaurants.html
> +<section class="home-restaurant-details">
тут класс section можна добавити а так все гуд

2023-02-26 08:38 UTC, ViktoriiaProtasova commented on src/partials/home/restaurants.html
> +<section class="home-restaurant-details">
Додала

2023-02-26 18:19 UTC, Mykokola approved these changes

2023-02-26 18:24 UTC, merged