added styles and markup
Mykokola/teams-project-17 pull request #8
Opened 2023-02-25 21:15 UTC by BozhiiKostya

2023-02-25 23:47 UTC, Mykokola requested changes

2023-02-25 23:47 UTC, Mykokola commented on src/partials/home/welcome-complex.html
> +    <picture>
Коли шира вюпорту 1440 картинка не підгружається

2023-02-25 23:48 UTC, Mykokola commented on src/partials/home/welcome-complex.html
> +    <picture>
ширина*

2023-02-27 03:43 UTC, BozhiiKostya commented on src/partials/home/welcome-complex.html
> +    <picture>
Поправил

2023-02-27 15:26 UTC, Mykokola approved these changes

2023-02-27 15:26 UTC, merged